### ISSUE TITLE
metrics cups emptys

### ISSUE THREAD

**Issue by hmunoz** [ThoreKr/cups_exporter#11]
This is my compose: 
metric-cups:
    image: thorekr/cups_exporter
    networks:
      - printer-cups
    ports:
      - 9329:9329
    environment:
           - CUPS_HOST=cupsd
           - CUPS_PORT=631
           - CUPS_USER=print
  cupsd:
    image: olbat/cupsd
    networks:
      - printer-cups
    ports:
      - 631:631
      
   
   This is metrics return:
  # HELP python_gc_objects_collected_total Objects collected during gc
# TYPE python_gc_objects_collected_total counter
python_gc_objects_collected_total{generation="0"} 90.0
python_gc_objects_collected_total{generation="1"} 286.0
python_gc_objects_collected_total{generation="2"} 0.0
# HELP python_gc_objects_uncollectable_total Uncollectable object found during GC
# TYPE python_gc_objects_uncollectable_total counter
python_gc_objects_uncollectable_total{generation="0"} 0.0
python_gc_objects_uncollectable_total{generation="1"} 0.0
python_gc_objects_uncollectable_total{generation="2"} 0.0
# HELP python_gc_collections_total Number of times this generation was collected
# TYPE python_gc_collections_total counter
python_gc_collections_total{generation="0"} 35.0
python_gc_collections_total{generation="1"} 3.0
python_gc_collections_total{generation="2"} 0.0
# HELP python_info Python platform information
# TYPE python_info gauge
python_info{implementation="CPython",major="3",minor="8",patchlevel="0",version="3.8.0"} 1.0
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 2.8717056e+07
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 1.6007168e+07
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.62264306314e+09
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 0.75
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 6.0
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1.048576e+06
# HELP cups_print_jobs_active Number of current print jobs
# TYPE cups_print_jobs_active gauge
# HELP cups_print_jobs_total Total number of print jobs
# TYPE cups_print_jobs_total counter
# HELP cups_printers Number of printers
# TYPE cups_printers gauge
# HELP cups_printer_status_info Status about printer alerts
# TYPE cups_printer_status_info gauge
# HELP cups_up CUPS status
# TYPE cups_up gauge
cups_up 0.0
# HELP cups_scrape_duration_seconds Amount of time each scrape takes
# TYPE cups_scrape_duration_seconds gauge
cups_scrape_duration_seconds 0.001664876937866211

**Comment by ThoreKr** [comment]
Looks like the exporter can't reach cupsd.

**Comment by hmunoz** [comment]
Docker compose define network internal. Services on same network. 
Server cups have a password, is a problem??
In the code exporter password not pass

**Comment by ThoreKr** [comment]
Probably? I don't know. Can you test it?

**Comment by hmunoz** [comment]
Now it works, I put the ip of the server in the host parameter and not the name of the compose service. (I have no idea why he doesn't accept it)

Now I stay like this, I am using prometheus and grafana to make a dashboard
We could generate a more complete project that I have the templates for grafana

```yml
version: '3.7'

networks:
  printer-cups:
    driver: overlay
    internal: true
    name: printer-cups

volumes:
    data-cupsd:
    data-grafana:
    prometheus-data:


services:
  prometheus:
    image: prom/prometheus:v2.27.1
    ports:
      - "9090:9090"
    networks:
      - printer-cups
    command:
      # Default commands from Dockerfile
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      # Our custom commands - metrics will be stored for 400 days
      - "--storage.tsdb.retention.time=400d"
      #- "--web.listen-address=127.0.0.1:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    networks:
      - printer-cups
    volumes:
      - data-grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=xxxx
      - GF_USERS_ALLOW_SIGN_UP=false
      #- GF_SERVER_DOMAIN=myrul.com
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=xxxx
      - GF_SMTP_PASSWORD=xxx
      - GF_SMTP_FROM_ADDRESS=xxx
  metric-cups:
    image: thorekr/cups_exporter
    networks:
      - printer-cups
    ports:
      - 9329:9329
    environment:
           - CUPS_HOST=IP-Server
           - CUPS_PORT=631
           - CUPS_USER=print

  cupsd:
    image: olbat/cupsd
    networks:
      - printer-cups
    ports:
      - 631:631
    volumes:
      - /var/run/dbus:/var/run/dbus
      - data-cupsd:/etc/cups/
 
```

```yml
global:
  scrape_interval: 60s
  evaluation_interval: 15s
  scrape_timeout: 50s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
      
  - job_name: 'cups'
    scrape_interval: 5s
    scheme: http
    static_configs:
      - targets: ['metric-cups:9329']
```
